use smningatreinamentogrupo1

-- CRIANDO TABELA DE CADASTRO

CREATE TABLE Cadastro_Colaborador (
	Id_CC INT PRIMARY KEY IDENTITY NOT NULL,
	Empresa VARCHAR (50) NOT NULL,
	Nome VARCHAR (255) NOT NULL,
	Email VARCHAR (300) NOT NULL,
	Cargo VARCHAR (50) NOT NULL,
	Cidade VARCHAR (50)
	)

-- CRIANDO TABELA DE TIPO DE CONTATO

CREATE TABLE Tipo_Contato (
	Id_Tipo INT PRIMARY KEY IDENTITY NOT NULL,
	Tipo VARCHAR (20) NOT NULL
    )

-- CRIANDO TABELA DE CONTATO

CREATE table  Contato (
	Id_Contato INT PRIMARY KEY IDENTITY NOT NULL,
	Id_CC INT NOT NULL,
	Id_Tipo INT NOT NULL,
	DDD TINYINT NOT NULL,
	Numero BIGINT NOT NULL,
	Whatsapp BIT NOT NULL,
	FOREIGN KEY (Id_CC) REFERENCES Cadastro_Colaborador (Id_CC),
	FOREIGN KEY (Id_Tipo) REFERENCES Tipo_Contato (Id_Tipo)
	)
