use smningatreinamentogrupo1

-- CRIANDO TABELA DE CADASTRO

CREATE TABLE CADASTRO_COLABORADOR (
	Id_CC INT PRIMARY KEY IDENTITY NOT NULL,
	Empresa VARCHAR (50) NOT NULL,
	Nome VARCHAR (255) NOT NULL,
	Email VARCHAR (300) NOT NULL,
	Cargo VARCHAR (50) NOT NULL,
	Cidade VARCHAR (50)
	)

-- CRIANDO TABELA DE TIPO DE CONTATO

CREATE TABLE TIPO_CONTATO (
	Id_Tipo INT PRIMARY KEY IDENTITY NOT NULL,
	TIPO VARCHAR (20) NOT NULL
    )

-- CRIANDO TABELA DE CONTATO

CREATE TABLE CONTATO (
	Id_Contato INT PRIMARY KEY IDENTITY NOT NULL,
	Id_CC INT NOT NULL,
	Id_Tipo INT NOT NULL,
	DDD TINYINT NOT NULL,
	Numero BIGINT NOT NULL,
	Whatsapp BIT NOT NULL,
	FOREIGN KEY (Id_CC) REFERENCES CADASTRO_COLABORADOR (Id_CC),
	FOREIGN KEY (Id_Tipo) REFERENCES TIPO_CONTATO (Id_Tipo)
	)
